### PR TITLE
feat: a magical web ui

### PR DESCRIPTION
**Pull request by olizilla**
packages visualised as moonlit ascii-trees that dance in the gloaming.

what-packages-do-in-dark

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

### CODE REVIEW

**Comment by olizilla** [comment]
more prosaically, it adds a web ui that scatters your list of packages across the page, each one represented by a ╪ that links to the npm page for that package.

the trees are distributed by their package name. locality is preserved such that packages with similar names will huddle together.

It is an HTML poem.

**Comment by alanshaw** [comment]
❤️ I LOVE IT

Only problem I can see is that I think @andrew added golang support so not all packages are npm packages anymore.

**Comment by andrew** [comment]
❤️

**Comment by andrew** [comment]
> Only problem I can see is that I think @andrew added golang support so not all packages are npm packages anymore.

go support will make api response look like:

```
[
  {
    "manager": "npm",
    "name": "es-get-iterator",
    "version": "1.1.2"
  },
  {
    "manager": "npm",
    "name": "get-intrinsic",
    "version": "1.1.0"
  },
  {
    "manager": "npm",
    "name": "is-callable",
    "version": "1.2.3"
  },
  {
    "manager": "npm",
    "name": "uglify-js",
    "version": "3.12.6"
  }
]
```

**Comment by andrew** [comment]
Fixed a conflict with master, merge when ready 🚀

**Comment by andrew** [comment]
Pushed some more fixes, plus enabled go module support

**Comment by andrew** [comment]
Also pushed a `$ forest browse` command that opens http://localhost:8005 in a browser

**Comment by olizilla** [comment]
packages visualised as moonlit ascii-trees that dance in the gloaming.

what-packages-do-in-dark

more prosaically, it adds a web ui that scatters your list of IPFS backed, forest hosted packages across the page, each one represented by a ╪ that links to the npm page for that package.

the trees are distributed by their package name. locality is preserved such that packages with similar names will huddle together.

It is an HTML poem.

**Pull request merged**
